from advanceLogger import ITimeFormatter


class IndexFormatter:
    def __init__(self, indicator: str, timestamper: ITimeFormatter):
        self.__timeFormatter = ...
        self.__indicator = ...
    def getIndex(self) -> str:...
